# Generated by Django 3.2 on 2021-05-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocked', to='listings.bookinginfo')),
                ('hotel_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.hotelroom')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.listing')),
            ],
        ),
    ]
