# Generated by Django 3.2 on 2021-05-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_reservation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('hotel_room', 'reserved_date'), name='uniq_room_rsv'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('listing', 'reserved_date'), name='uniq_apartment_rsv'),
        ),
    ]
